/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_com_easyrtc_Device
#define _Included_com_easyrtc_Device


#define JNI_VERSION JNI_VERSION_1_4
#include <android/log.h>


#ifdef __cplusplus
extern "C" {
#endif

extern JavaVM *g_vm;
#if 1//def __DEBUG__
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG  , "EASYDARWIN", __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR  , "EASYDARWIN", __VA_ARGS__)
#else
#define LOGD(...)
#define LOGE(...)
#endif

JNIEXPORT jint JNICALL Java_cn_easyrtc_device_PassiveCallResponse
        (JNIEnv* pEnv, jobject obj, jstring peerUUID, jint decline);

JNIEXPORT jint JNICALL Java_cn_easyrtc_device_create
    (JNIEnv *pEnv, jobject obj, jint version, jstring serverAddr, jint serverPort, jstring password, jstring localId, jint channelNum, jint userptr);

JNIEXPORT jint JNICALL Java_cn_easyrtc_device_SetChannelInfo
(JNIEnv* pEnv, jobject obj, jint channelId, jstring channelIDStr, jint videoCodecID, jint audioCodecID);

JNIEXPORT jint JNICALL Java_cn_easyrtc_device_Hangup
(JNIEnv* pEnv, jobject obj, jstring peerUUID);

JNIEXPORT jint JNICALL Java_cn_easyrtc_device_SendVideoFrame
    (JNIEnv *pEnv, jobject obj, jint channelId, jbyteArray framedata, jint framesize, jint keyframe, jint pts);

JNIEXPORT jint JNICALL Java_cn_easyrtc_device_SendAudioFrame
(JNIEnv* pEnv, jobject obj, jint channelId, jbyteArray framedata, jint framesize, jint pts);

JNIEXPORT jint JNICALL Java_cn_easyrtc_device_SendMetadata
(JNIEnv* pEnv, jobject obj, jint channelId, jstring msg, jint size);


//JNIEXPORT jint JNICALL Java_cn_easyrtc_device_GetOnlineClients
//(JNIEnv* pEnv, jobject obj);
//
//
//
//JNIEXPORT jint JNICALL Java_cn_easyrtc_device_OpenPeerConnection
//(JNIEnv* pEnv, jobject obj, jstring peerUUID);
//
//
//JNIEXPORT jint JNICALL Java_cn_easyrtc_device_ClosePeerConnection
//(JNIEnv* pEnv, jobject obj, jstring peerUUID);
//
//
//JNIEXPORT jint JNICALL Java_cn_easyrtc_device_HandleCall
//(JNIEnv* pEnv, jobject obj, jstring peerUUID, jint isAccepted);


JNIEXPORT jint JNICALL Java_cn_easyrtc_device_release
  (JNIEnv *, jobject);




#ifdef __cplusplus
}
#endif
#endif
